# Generated by Django 4.2.18 on 2025-04-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='header_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='avatar_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
