# Generated by Django 4.2.20 on 2025-10-29 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_character_header_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='greeting',
            field=models.TextField(blank=True, null=True),
        ),
    ]
