# Generated by Django 4.2.20 on 2025-10-29 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_character_greeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
