# Generated by Django 4.2.20 on 2025-10-29 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_character_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
